<?php

declare(strict_types=1);

namespace Semitexa\Dev\Application\Service\Explorer;

use Psr\Container\ContainerInterface;
use Semitexa\Core\Attribute\AsService;
use Semitexa\Core\Attribute\InjectAsReadonly;
use Semitexa\Core\Environment;

/**
 * An OpenAPI 3.1 document for EVERY route — what Postman or Insomnia imports.
 *
 * semitexa/api's `openapi:dump` describes only routes that return a
 * registered resource as JSON, seven in the demo app. This one is built from
 * the Explorer's catalog — the same attributes the router reads — so every
 * endpoint is in it: path parameters, the payload's fields as query
 * parameters (bodyless methods) or a request body, auth per access type.
 *
 * Where semitexa/api is installed, its richer answer wins for the routes it
 * knows: its response schemas and collection parameters are laid over these
 * operations. Looked up by name, never imported — dev does not require api.
 */
#[AsService]
final class OpenApiExporter
{
    private const API_BUILDER = 'Semitexa\\Api\\OpenApi\\OpenApiDocumentBuilder';
    private const BODYLESS = ['GET', 'DELETE'];
    private const TYPES = ['int' => 'integer', 'float' => 'number', 'bool' => 'boolean', 'array' => 'array', 'string' => 'string'];
    private const FORMATS = ['email' => 'email', 'url' => 'uri', 'uuid' => 'uuid', 'date' => 'date', 'datetime' => 'date-time', 'password' => 'password'];
    private const MEDIA = [RouteKind::Page->value => 'text/html', RouteKind::Stream->value => 'text/event-stream'];

    #[InjectAsReadonly]
    protected RouteCatalog $catalog;

    #[InjectAsReadonly]
    protected ContainerInterface $container;

    /**
     * @param list<RouteKind> $kinds which kinds of route to describe
     * @return array<string, mixed>
     */
    public function build(array $kinds): array
    {
        $paths = [];
        $operationIds = [];
        foreach ($this->catalog->entries() as $entry) {
            if (!in_array($entry->kind, $kinds, true)) {
                continue;
            }
            $contract = $this->catalog->contract($entry) ?? [];
            $hints = FieldHintReflector::hints($entry->payload);
            $path = self::openApiPath($entry->path);
            foreach ($entry->methods as $method) {
                $operation = self::operation($entry, $method, $contract, $hints);
                $operation['operationId'] = self::uniqueId($operation['operationId'], $operationIds);
                $paths[$path][strtolower($method)] = $operation;
            }
        }

        $document = [
            'openapi' => '3.1.0',
            'info' => [
                'title' => (Environment::getEnvValue('APP_NAME') ?? 'Semitexa app') . ' — all routes',
                'version' => 'dev',
                'description' => 'Generated by the Semitexa API Explorer from route attributes. Validation that lives inside payload setters is not visible here.',
            ],
            'servers' => [['url' => '/']],
            'paths' => $paths === [] ? (object) [] : $paths,
            'components' => [
                'securitySchemes' => [
                    'session' => ['type' => 'apiKey', 'in' => 'cookie', 'name' => Environment::getEnvValue('SESSION_COOKIE_NAME') ?? 'semitexa_session'],
                    'service' => ['type' => 'http', 'scheme' => 'bearer'],
                ],
            ],
        ];

        return $this->overlayApiPackage($document);
    }

    /**
     * @param array<string, mixed> $contract
     * @param array<string, array<string, mixed>> $hints
     * @return array<string, mixed>
     */
    private static function operation(CatalogEntry $entry, string $method, array $contract, array $hints): array
    {
        $fields = $contract['input']['fields'] ?? $contract['fields'] ?? [];
        $fields = is_array($fields) ? array_values(array_filter($fields, 'is_array')) : [];

        $parameters = [];
        foreach ($entry->pathParams as $param) {
            $schema = ['type' => 'string'];
            if (isset($entry->requirements[$param])) {
                $schema['pattern'] = '^' . $entry->requirements[$param] . '$';
            }
            $parameters[] = ['name' => $param, 'in' => 'path', 'required' => true, 'schema' => $schema];
        }

        $inputs = array_values(array_filter($fields, static fn (array $f): bool => !in_array($f['name'] ?? null, $entry->pathParams, true)));
        $operation = [
            'operationId' => $entry->name !== null && $entry->name !== '' ? $entry->name : self::short($entry->payload) . ucfirst(strtolower($method)),
            'summary' => $entry->name !== null && $entry->name !== '' ? $entry->name : self::short($entry->payload),
            'tags' => [$entry->module !== '' ? $entry->module : 'app'],
        ];

        if (in_array($method, self::BODYLESS, true)) {
            foreach ($inputs as $field) {
                $parameters[] = [
                    'name' => (string) $field['name'],
                    'in' => 'query',
                    'required' => ($field['required'] ?? false) === true,
                    'schema' => self::schema($field, $hints[$field['name']] ?? []),
                ];
            }
        } elseif ($inputs !== []) {
            $properties = [];
            $required = [];
            foreach ($inputs as $field) {
                $properties[(string) $field['name']] = self::schema($field, $hints[$field['name']] ?? []);
                if (($field['required'] ?? false) === true) {
                    $required[] = (string) $field['name'];
                }
            }
            $body = ['type' => 'object', 'properties' => $properties];
            if ($required !== []) {
                $body['required'] = $required;
            }
            $operation['requestBody'] = ['content' => [
                'application/json' => ['schema' => $body],
                'application/x-www-form-urlencoded' => ['schema' => $body],
            ]];
        }

        if ($parameters !== []) {
            $operation['parameters'] = $parameters;
        }

        $media = self::MEDIA[$entry->kind->value] ?? 'application/json';
        $operation['responses'] = ['200' => ['description' => 'OK', 'content' => [$media => (object) []]]];
        if ($entry->access !== 'public') {
            $operation['responses']['401'] = ['description' => 'Authentication required'];
            $operation['security'] = [[$entry->access === 'service' ? 'service' : 'session' => []]];
        }
        if ($inputs !== []) {
            $operation['responses']['422'] = ['description' => 'Validation failed'];
        }

        $operation['x-semitexa'] = array_filter([
            'kind' => $entry->kind->value,
            'access' => $entry->access,
            'payload' => $entry->payload,
            'handler' => $entry->handler,
            'response' => $entry->response,
        ]);

        return $operation;
    }

    /**
     * @param array<string, mixed> $field
     * @param array<string, mixed> $hint
     * @return array<string, mixed>
     */
    private static function schema(array $field, array $hint): array
    {
        $raw = is_string($field['type'] ?? null) ? ltrim($field['type'], '?') : 'mixed';
        $type = self::TYPES[$raw] ?? null;
        $schema = $type === null ? [] : ['type' => ($field['nullable'] ?? false) === true ? [$type, 'null'] : $type];
        if ($type === 'array') {
            $schema['items'] = (object) [];
        }
        if (isset($hint['enum']) && is_array($hint['enum'])) {
            $schema['enum'] = $hint['enum'];
        }
        if (array_key_exists('default', $hint)) {
            $schema['default'] = $hint['default'];
        }
        if (is_string($hint['format'] ?? null) && isset(self::FORMATS[$hint['format']])) {
            $schema['format'] = self::FORMATS[$hint['format']];
        }

        return $schema;
    }

    /**
     * Lays semitexa/api's operations over ours: its response schemas and the
     * collection parameters (page, sort, filter…) it knows and the catalog
     * does not. Anything going wrong there leaves the catalog's document as is.
     *
     * @param array<string, mixed> $document
     * @return array<string, mixed>
     */
    private function overlayApiPackage(array $document): array
    {
        if (!class_exists(self::API_BUILDER) || !$this->container->has(self::API_BUILDER)) {
            return $document;
        }
        try {
            $api = $this->container->get(self::API_BUILDER)->build();
        } catch (\Throwable) {
            $document['info']['description'] .= ' semitexa/api could not add its resource schemas.';

            return $document;
        }

        foreach ((array) ($api['paths'] ?? []) as $path => $operations) {
            foreach ((array) $operations as $method => $apiOperation) {
                if (!is_array($apiOperation) || !isset($document['paths'][$path][$method])) {
                    continue;
                }
                $ours = &$document['paths'][$path][$method];
                if (isset($apiOperation['responses'])) {
                    $ours['responses'] = $apiOperation['responses'] + $ours['responses'];
                }
                $known = array_map(static fn (array $p): string => $p['in'] . ':' . $p['name'], $ours['parameters'] ?? []);
                foreach ($apiOperation['parameters'] ?? [] as $parameter) {
                    if (is_array($parameter) && !in_array(($parameter['in'] ?? '') . ':' . ($parameter['name'] ?? ''), $known, true)) {
                        $ours['parameters'][] = $parameter;
                    }
                }
                unset($ours);
            }
        }
        $schemas = (array) ($api['components']['schemas'] ?? []);
        if ($schemas !== []) {
            $document['components']['schemas'] = $schemas;
        }

        return $document;
    }

    public static function openApiPath(string $path): string
    {
        return (string) preg_replace('/\{([A-Za-z_][A-Za-z0-9_]*)[^}]*\}/', '{$1}', $path);
    }

    /** @param array<string, true> $taken */
    private static function uniqueId(string $id, array &$taken): string
    {
        $candidate = $id;
        for ($n = 2; isset($taken[$candidate]); $n++) {
            $candidate = $id . $n;
        }
        $taken[$candidate] = true;

        return $candidate;
    }

    private static function short(string $fqcn): string
    {
        $short = substr((string) strrchr('\\' . $fqcn, '\\'), 1);

        return (string) preg_replace('/Payload$/', '', $short);
    }
}
