#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Skill-local release helper for Semitexa packages.
 *
 * This version is pinned to the release clone and intentionally keeps only the
 * release-safe mode:
 * 1. Fetch origin/master and tags for each standalone package repo.
 * 2. Update the local master ref to match origin/master.
 * 3. Use the UTC release version generated by the release session.
 * 4. If master HEAD is untagged, create that tag and push it.
 * 5. Rebuild semitexa/ultimate exact internal dependency pins from the actual
 *    released versions, commit that manifest on develop, fast-forward master
 *    to that pin-refresh commit, and tag it last.
 * 6. Trigger and verify Packagist updates when credentials are available.
 * 7. Write the release summary before external publication polling so the
 *    release report can still be finalized if verification stalls.
 *
 * Usage:
 *   php scripts/bump-packages.php
 *   php scripts/bump-packages.php semitexa/core
 *   php scripts/bump-packages.php --no-push
 *   php scripts/bump-packages.php --dry-run
 *   php scripts/bump-packages.php --yes
 *   php scripts/bump-packages.php --release-version 2026.04.03.1315
 *   php scripts/bump-packages.php --help
 */

// Refuse to execute when the script is included/required rather than invoked
// directly via CLI. Defines may still be loaded by callers that explicitly opt
// out via `define('BUMP_PACKAGES_LIBRARY_MODE', true)` before include.
$invokedScript = $_SERVER['argv'][0] ?? '';
$invokedScript = $invokedScript !== '' ? (realpath($invokedScript) ?: $invokedScript) : '';
if (PHP_SAPI !== 'cli' || $invokedScript !== __FILE__) {
    if (defined('BUMP_PACKAGES_LIBRARY_MODE') && BUMP_PACKAGES_LIBRARY_MODE) {
        return;
    }
    fwrite(
        STDERR,
        "bump-packages.php must be invoked directly via `php scripts/bump-packages.php`, not include/require.\n"
    );
    exit(1);
}

$expectedRootDir = '/home/taras/Documents/Projects/semitexa.rls';
$rootDir = getenv('RELEASE_ROOT') ?: $expectedRootDir;
$rootDir = rtrim($rootDir, DIRECTORY_SEPARATOR);

$resolvedRootDir = realpath($rootDir);
$resolvedExpectedRootDir = realpath($expectedRootDir);

if ($resolvedRootDir === false || $resolvedExpectedRootDir === false || $resolvedRootDir !== $resolvedExpectedRootDir) {
    fwrite(
        STDERR,
        "This skill-local release tagger is pinned to {$expectedRootDir} and refuses to run against {$rootDir}.\n"
    );
    exit(1);
}

$rootDir = $resolvedRootDir;
$packagesDir = $rootDir . '/packages';

$envFile = $rootDir . '/.env';
if (is_file($envFile)) {
    $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') {
            continue;
        }
        if (strpos($line, '=') === false) {
            continue;
        }
        [$key, $val] = explode('=', $line, 2);
        $key = trim($key);
        $val = trim($val, " \t\"'");
        if ($key !== '' && getenv($key) === false) {
            putenv($key . '=' . $val);
        }
    }
}

$args = array_slice($argv, 1);
$noPush = in_array('--no-push', $args, true);
$dryRun = in_array('--dry-run', $args, true);
$assumeYes = in_array('--yes', $args, true) || in_array('-y', $args, true);
$showHelp = in_array('--help', $args, true) || in_array('-h', $args, true);
$summaryJsonPath = extractOptionValue($args, '--summary-json');
$releaseVersion = extractOptionValue($args, '--release-version') ?: (getenv('RELEASE_VERSION') ?: '');
$releaseChannel = getenv('RELEASE_CHANNEL') ?: 'stable';
$releaseCodename = getenv('RELEASE_CODENAME') ?: '';
$releaseGeneratedAtUtc = getenv('RELEASE_GENERATED_AT_UTC') ?: gmdate('Y-m-d\TH:i:00\Z');
$filterByName = null;
foreach ($args as $arg) {
    if ($arg === $summaryJsonPath) {
        continue;
    }
    if (!str_starts_with($arg, '--')) {
        $filterByName = $arg;
        break;
    }
}

if ($showHelp) {
    printUsage();
    exit(0);
}

if ($releaseVersion === '' || !isReleaseTag($releaseVersion)) {
    fwrite(STDERR, "RELEASE_VERSION is required and must match the Semitexa UTC release format.\n");
    exit(1);
}

if (!is_dir($packagesDir)) {
    fwrite(STDERR, "Packages directory not found: {$packagesDir}\n");
    exit(1);
}

$dirs = array_filter(
    glob($packagesDir . '/*', GLOB_ONLYDIR) ?: [],
    static fn(string $d) => is_file($d . '/composer.json'),
);

$errors = 0;
$candidates = [];
$skipped = 0;
$skippedAheadOfMaster = [];
$packageStates = [];
$ultimatePlan = null;
$ultimatePreviewCandidate = null;

echo "\033[1m--- Scanning packages for untagged master HEAD commits ---\033[0m\n";
echo "Release channel: {$releaseChannel}\n";
echo "Release codename: " . ($releaseCodename !== '' ? ucfirst($releaseCodename) : 'n/a') . "\n";
echo "Release version: {$releaseVersion}\n\n";

foreach ($dirs as $dir) {
    $composerPath = $dir . '/composer.json';
    $json = @file_get_contents($composerPath);
    if ($json === false) {
        fwrite(STDERR, "Cannot read: {$composerPath}\n");
        $errors++;
        continue;
    }

    $data = json_decode($json, true);
    if (!is_array($data)) {
        fwrite(STDERR, "Invalid JSON: {$composerPath}\n");
        $errors++;
        continue;
    }

    $name = $data['name'] ?? null;
    if ($name === null || $name === '') {
        fwrite(STDERR, "Missing 'name' in {$composerPath}\n");
        $errors++;
        continue;
    }

    if ($filterByName !== null && $name !== $filterByName) {
        continue;
    }

    $packageDir = dirname($composerPath);
    if (!is_dir($packageDir . '/.git')) {
        fwrite(STDERR, "Skipping {$name}: release mode requires a standalone git repo in {$packageDir}\n");
        $skipped++;
        continue;
    }

    if (!syncLocalBranch($packageDir, 'master')) {
        fwrite(STDERR, "Skipping {$name}: could not fetch/sync origin/master\n");
        $skipped++;
        continue;
    }

    $state = packageReleaseState($packageDir);
    if ($state === null) {
        $skipped++;
        continue;
    }

    $packageStates[$name] = [
        'name' => $name,
        'composer_path' => $composerPath,
        'package_dir' => $packageDir,
        'latest_tag' => $state['latest_tag'],
        'current_release_version' => $state['current_release_version'],
        'head_sha' => $state['head_sha'],
        'head_sha_short' => $state['head_sha_short'],
        'head_subject' => $state['head_subject'],
        'head_has_release_tag' => $state['head_has_release_tag'],
    ];

    if ($name === 'semitexa/ultimate') {
        $ultimatePlan = [
            'name' => $name,
            'composer_path' => $composerPath,
            'package_dir' => $packageDir,
            'composer' => $data,
            'info' => $state,
        ];
        continue;
    }

    $info = packageHeadNeedsTag($packageDir);
    if ($info === null) {
        $skipped++;
        continue;
    }

    if ($info['head_has_release_tag']) {
        $skipped++;
        $divergence = developAheadOfMaster($packageDir);
        if ($divergence !== null && $divergence['ahead'] > 0) {
            $skippedAheadOfMaster[] = [
                'name' => $name,
                'master_sha_short' => $info['head_sha_short'],
                'tag' => $packageStates[$name]['current_release_version'] ?? ($info['latest_tag'] ?? 'unknown'),
                'develop_sha_short' => $divergence['develop_sha_short'],
                'ahead' => $divergence['ahead'],
            ];
        }
        continue;
    }

    $candidates[] = [
        'name' => $name,
        'version' => $releaseVersion,
        'current_version' => $info['latest_tag'] ?? 'none',
        'composer_path' => $composerPath,
        'package_dir' => $packageDir,
        'info' => $info,
        'changes' => collectReleaseChanges($packageDir, $info['latest_tag']),
    ];
}

if ($filterByName !== null && $candidates === [] && $errors === 0 && $filterByName !== 'semitexa/ultimate') {
    fwrite(STDERR, "No package found with name '{$filterByName}', or its master HEAD is already tagged.\n");
    exit(1);
}

if ($errors > 0) {
    exit(1);
}

if ($ultimatePlan !== null) {
    $plannedReleasedPackages = array_map(
        static fn(array $candidate): array => [
            'name' => $candidate['name'],
            'version' => $candidate['version'],
            'info' => $candidate['info'],
        ],
        $candidates,
    );
    $ultimatePreviewCandidate = buildUltimateReleaseCandidate($ultimatePlan, $packageStates, $plannedReleasedPackages);
}

if ($candidates === [] && $ultimatePreviewCandidate === null) {
    if ($summaryJsonPath !== null) {
        writeReleaseSummary($summaryJsonPath, [], $rootDir, $noPush, $dryRun);
    }

    printDevelopAheadWarning($skippedAheadOfMaster);

    echo "All packages are up to date. Nothing to release.";
    if ($skipped > 0) {
        echo " ({$skipped} package(s) already tagged)";
    }
    echo "\n";
    exit(0);
}

echo sprintf(
    "\033[1m%d package(s) to tag on master HEAD:\033[0m\n\n",
    count($candidates) + ($ultimatePreviewCandidate !== null ? 1 : 0),
);

foreach ($candidates as $c) {
    $info = $c['info'];
    echo sprintf(
        "  \033[32m%s\033[0m  %s → \033[1m%s\033[0m  (master @ %s)\n",
        $c['name'],
        $c['current_version'],
        $c['version'],
        $info['head_sha_short'],
    );
    echo "    • {$info['head_subject']}\n\n";
}

if ($ultimatePreviewCandidate !== null) {
    $info = $ultimatePreviewCandidate['info'];
    echo sprintf(
        "  \033[32m%s\033[0m  %s → \033[1m%s\033[0m  (master @ %s)\n",
        $ultimatePreviewCandidate['name'],
        $ultimatePreviewCandidate['current_version'],
        $ultimatePreviewCandidate['version'],
        $info['head_sha_short'],
    );
    echo "    • {$info['head_subject']}\n\n";
}

printDevelopAheadWarning($skippedAheadOfMaster);

if ($dryRun) {
    echo "Dry run only. No changes were made.\n";
    exit(0);
}

if (!$assumeYes) {
    echo !$noPush
        ? "This will create tags and \033[1mpush\033[0m them to origin. Continue? [Y/n] "
        : "This will create tags locally (no push). Continue? [Y/n] ";

    $answer = trim((string) fgets(STDIN));
    if ($answer !== '' && strtolower($answer[0]) !== 'y') {
        echo "Aborted.\n";
        exit(0);
    }
}

echo "\n\033[1m--- Releasing ---\033[0m\n\n";

$updatedPackages = [];

foreach ($candidates as $c) {
    echo "\033[36m{$c['name']}\033[0m {$c['current_version']} → {$c['version']}...\n";
    $c['released_at'] = gmdate(DATE_ATOM);
    $c = releaseMasterHead($c, $c['version'], $noPush);
    $updatedPackages[] = $c;
}

if ($ultimatePlan !== null) {
    $ultimateRelease = buildUltimateReleaseCandidate($ultimatePlan, $packageStates, $updatedPackages);
    if ($ultimateRelease !== null) {
        if ($filterByName === null || $filterByName === 'semitexa/ultimate') {
            echo "\033[36m{$ultimateRelease['name']}\033[0m {$ultimateRelease['current_version']} → {$ultimateRelease['version']}...\n";
            $ultimateRelease['released_at'] = gmdate(DATE_ATOM);
            $ultimateRelease = releaseUltimateManifest($ultimateRelease, $noPush);
            $updatedPackages[] = $ultimateRelease;
        }
    } elseif ($filterByName === 'semitexa/ultimate') {
        fwrite(STDERR, "semitexa/ultimate is already aligned to the currently released internal package versions.\n");
        exit(1);
    }
}

if ($summaryJsonPath !== null) {
    writeReleaseSummary($summaryJsonPath, $updatedPackages, $rootDir, $noPush, $dryRun);
}

if ($updatedPackages !== [] && !$noPush) {
    echo "\n";
    notifyPackagistForPackages($updatedPackages);
    verifyPackagistForPackages($updatedPackages);
}

echo "\n\033[1;32mDone.\033[0m Released " . count($updatedPackages) . " package(s).\n";

function printUsage(): void
{
    echo <<<TXT
Usage:
  php scripts/bump-packages.php
  php scripts/bump-packages.php semitexa/core
  php scripts/bump-packages.php --no-push
  php scripts/bump-packages.php --dry-run
  php scripts/bump-packages.php --yes
  php scripts/bump-packages.php --release-version 2026.04.03.1315
  php scripts/bump-packages.php --summary-json /tmp/release-summary.json

TXT;
}

function extractOptionValue(array $args, string $option): ?string
{
    $count = count($args);
    for ($i = 0; $i < $count; $i++) {
        $arg = $args[$i];
        if ($arg === $option) {
            $next = $args[$i + 1] ?? null;
            return is_string($next) && $next !== '' ? $next : null;
        }

        $prefix = $option . '=';
        if (str_starts_with($arg, $prefix)) {
            $value = substr($arg, strlen($prefix));
            return $value !== '' ? $value : null;
        }
    }

    return null;
}

function syncLocalBranch(string $packageDir, string $branch): bool
{
    if (!fetchRemoteBranch($packageDir, $branch)) {
        return false;
    }

    $originBranchRef = 'refs/remotes/origin/' . $branch;
    $localBranchRef = 'refs/heads/' . $branch;
    $cmd = sprintf(
        'git -C %s rev-parse --verify %s 2>/dev/null',
        escapeshellarg($packageDir),
        escapeshellarg($originBranchRef),
    );
    $targetSha = trim((string) shell_exec($cmd));
    if ($targetSha === '') {
        return false;
    }

    $currentBranch = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' rev-parse --abbrev-ref HEAD 2>/dev/null'
    ));

    if ($currentBranch === $branch) {
        $cmd = 'git -C ' . escapeshellarg($packageDir) . ' status --porcelain -u 2>/dev/null';
        $out = [];
        exec($cmd, $out, $code);
        if ($code !== 0 || !empty(array_filter($out, static fn(string $line) => trim($line) !== ''))) {
            fwrite(STDERR, "Cannot sync local {$branch} in {$packageDir}: working tree on {$branch} is dirty.\n");
            return false;
        }

        runGit($packageDir, 'reset', '--hard', $originBranchRef);
        return true;
    }

    runGit($packageDir, 'update-ref', $localBranchRef, $targetSha);
    return true;
}

function correspondingAuthoringRepoDir(string $releasePackageDir): ?string
{
    $authoringRoot = getenv('SEMITEXA_DEV_ROOT');
    if ($authoringRoot !== false && $authoringRoot !== '') {
        $candidate = rtrim($authoringRoot, '/\\') . '/packages/' . basename($releasePackageDir);
        return is_dir($candidate . '/.git') ? $candidate : null;
    }

    $candidate = str_replace('/semitexa.rls/packages/', '/semitexa.dev/packages/', $releasePackageDir);
    if ($candidate === $releasePackageDir) {
        return null;
    }

    return is_dir($candidate . '/.git') ? $candidate : null;
}

function syncAuthoringRepoBranches(string $releasePackageDir, array $branches): void
{
    $authoringRepoDir = correspondingAuthoringRepoDir($releasePackageDir);
    if ($authoringRepoDir === null) {
        return;
    }

    foreach ($branches as $branch) {
        if (syncLocalBranch($authoringRepoDir, $branch)) {
            continue;
        }

        fwrite(
            STDERR,
            "Warning: skipped syncing local authoring checkout {$authoringRepoDir} branch {$branch} after release.\n"
        );
    }
}

function packageReleaseState(string $packageDir): ?array
{
    $latestTag = latestMergedReleaseTag($packageDir);

    $cmd = sprintf(
        'git -C %s rev-parse --verify master 2>/dev/null',
        escapeshellarg($packageDir),
    );
    $headSha = trim((string) shell_exec($cmd));
    if ($headSha === '') {
        return null;
    }

    $cmd = sprintf(
        'git -C %s tag --points-at %s 2>/dev/null',
        escapeshellarg($packageDir),
        escapeshellarg($headSha),
    );
    $out = [];
    exec($cmd, $out);
    $headTags = array_values(array_filter(
        array_map('trim', $out),
        static fn(string $tag) => isReleaseTag($tag),
    ));

    $cmd = sprintf(
        'git -C %s log -1 --format=%%s master 2>/dev/null',
        escapeshellarg($packageDir),
    );
    $headSubject = trim((string) shell_exec($cmd));

    $currentReleaseVersion = $headTags !== []
        ? normalizeVersion($headTags[0])
        : ($latestTag !== null ? normalizeVersion($latestTag) : null);

    return [
        'latest_tag' => $latestTag,
        'current_release_version' => $currentReleaseVersion,
        'head_sha' => $headSha,
        'head_sha_short' => substr($headSha, 0, 8),
        'head_subject' => $headSubject !== '' ? $headSubject : '(no commit subject)',
        'head_has_release_tag' => $headTags !== [],
    ];
}

function packageHeadNeedsTag(string $packageDir): ?array
{
    $latestTag = latestMergedReleaseTag($packageDir);

    $cmd = sprintf(
        'git -C %s rev-parse --verify master 2>/dev/null',
        escapeshellarg($packageDir),
    );
    $headSha = trim((string) shell_exec($cmd));
    if ($headSha === '') {
        return null;
    }

    $cmd = sprintf(
        'git -C %s tag --points-at %s 2>/dev/null',
        escapeshellarg($packageDir),
        escapeshellarg($headSha),
    );
    $out = [];
    exec($cmd, $out);
    $headTags = array_values(array_filter(
        array_map('trim', $out),
        static fn(string $tag) => isReleaseTag($tag),
    ));
    if ($headTags !== []) {
        return null;
    }

    $cmd = sprintf(
        'git -C %s log -1 --format=%%s master 2>/dev/null',
        escapeshellarg($packageDir),
    );
    $headSubject = trim((string) shell_exec($cmd));

    return [
        'latest_tag' => $latestTag,
        'head_sha' => $headSha,
        'head_sha_short' => substr($headSha, 0, 8),
        'head_subject' => $headSubject !== '' ? $headSubject : '(no commit subject)',
        'head_has_release_tag' => $headTags !== [],
    ];
}

function releaseMasterHead(array $package, string $nextVersion, bool $noPush): array
{
    $packageDir = $package['package_dir'];
    $name = $package['name'];
    $tagName = versionTag($nextVersion);
    $status = runShellCommand('git -C ' . escapeshellarg($packageDir) . ' status --porcelain -u 2>/dev/null');
    if ($status['exit_code'] !== 0 || $status['output'] !== '') {
        fwrite(STDERR, "Cannot prepare release for {$name}: working tree is not clean.\n");
        exit(1);
    }

    $currentBranch = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' rev-parse --abbrev-ref HEAD 2>/dev/null'
    ));
    if ($currentBranch !== 'master') {
        runGit($packageDir, 'checkout', 'master');
    }

    runGit($packageDir, 'reset', '--hard', 'origin/master');
    runGit($packageDir, 'tag', '-m', 'Release ' . $tagName, $tagName, 'HEAD');

    $headSha = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' rev-parse --verify HEAD 2>/dev/null'
    ));
    $headSubject = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' log -1 --format=%s HEAD 2>/dev/null'
    ));
    $package['info']['head_sha'] = $headSha;
    $package['info']['head_sha_short'] = substr($headSha, 0, 8);
    $package['info']['head_subject'] = $headSubject !== '' ? $headSubject : '(no commit subject)';
    $package['info']['head_has_release_tag'] = true;

    if ($noPush) {
        echo "  Tagged {$name} {$tagName} locally on existing master HEAD (not pushed)\n";
        return $package;
    }

    runGit($packageDir, 'push', 'origin', 'refs/tags/' . $tagName . ':refs/tags/' . $tagName);
    echo "  Pushed {$name} {$tagName} for master HEAD {$package['info']['head_sha_short']}\n";
    return $package;
}

function buildUltimateReleaseCandidate(array $ultimatePlan, array $packageStates, array $releasedPackages): ?array
{
    $currentRequire = $ultimatePlan['composer']['require'] ?? [];
    $currentRequireDev = $ultimatePlan['composer']['require-dev'] ?? [];
    if (!is_array($currentRequire) || !is_array($currentRequireDev)) {
        return null;
    }

    assertUltimateDependenciesArePresent($currentRequire, $packageStates);
    assertUltimateDependenciesArePresent($currentRequireDev, $packageStates);

    $releasedVersions = releasedVersionsMap($packageStates, $releasedPackages);
    $updatedRequire = buildPinnedRequirements($currentRequire, $releasedVersions);
    $updatedRequireDev = buildPinnedRequirements($currentRequireDev, $releasedVersions);
    $pinsChanged = $updatedRequire !== $currentRequire || $updatedRequireDev !== $currentRequireDev;

    $currentVersion = $ultimatePlan['info']['current_release_version'] ?? 'none';
    if (!$pinsChanged && ($ultimatePlan['info']['head_has_release_tag'] ?? false) === true) {
        return null;
    }

    $candidate = [
        'name' => $ultimatePlan['name'],
        'version' => getenv('RELEASE_VERSION') ?: '',
        'current_version' => $currentVersion,
        'composer_path' => $ultimatePlan['composer_path'],
        'package_dir' => $ultimatePlan['package_dir'],
        'info' => [
            'latest_tag' => $ultimatePlan['info']['latest_tag'],
            'head_sha' => $ultimatePlan['info']['head_sha'],
            'head_sha_short' => $ultimatePlan['info']['head_sha_short'],
            'head_subject' => $pinsChanged
                ? 'Pin internal Semitexa package versions for release'
                : $ultimatePlan['info']['head_subject'],
            'head_has_release_tag' => false,
        ],
        'changes' => [],
        'updated_require' => $updatedRequire,
        'updated_require_dev' => $updatedRequireDev,
        'pins_changed' => $pinsChanged,
    ];

    foreach ($releasedPackages as $package) {
        $candidate['changes'][] = [
            'sha' => $package['info']['head_sha'] ?? '',
            'subject' => sprintf('Pin %s to %s', $package['name'], $package['version']),
        ];
    }

    return $candidate;
}

function releasedVersionsMap(array $packageStates, array $releasedPackages): array
{
    $versions = [];

    foreach ($packageStates as $name => $state) {
        $version = $state['current_release_version'] ?? null;
        if (is_string($version) && $version !== '') {
            $versions[$name] = $version;
        }
    }

    foreach ($releasedPackages as $package) {
        $versions[$package['name']] = (string) $package['version'];
    }

    return $versions;
}

function assertUltimateDependenciesArePresent(array $requirements, array $packageStates): void
{
    $missingPackages = [];

    foreach ($requirements as $packageName => $constraint) {
        if (!is_string($packageName) || !str_starts_with($packageName, 'semitexa/') || $packageName === 'semitexa/ultimate') {
            continue;
        }

        if (!array_key_exists($packageName, $packageStates)) {
            $missingPackages[] = $packageName;
        }
    }

    if ($missingPackages === []) {
        return;
    }

    sort($missingPackages);
    throw new RuntimeException(
        'Release set is missing internal packages required by semitexa/ultimate: ' . implode(', ', $missingPackages)
    );
}

function buildPinnedRequirements(array $requirements, array $releasedVersions): array
{
    $updated = $requirements;

    foreach ($requirements as $packageName => $constraint) {
        if (!is_string($packageName) || !str_starts_with($packageName, 'semitexa/') || $packageName === 'semitexa/ultimate') {
            continue;
        }

        if (!isset($releasedVersions[$packageName])) {
            continue;
        }

        $updated[$packageName] = $releasedVersions[$packageName];
    }

    return $updated;
}

function updateComposerRequirements(string $composerPath, array $requirements, array $requireDev): void
{
    $json = json_decode((string) file_get_contents($composerPath), true);
    if (!is_array($json)) {
        throw new RuntimeException("Invalid JSON: {$composerPath}");
    }

    $json['require'] = $requirements;
    $json['require-dev'] = $requireDev;
    file_put_contents($composerPath, json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL);
}

function releaseUltimateManifest(array $package, bool $noPush): array
{
    $packageDir = $package['package_dir'];
    $name = $package['name'];
    $tagName = versionTag((string) $package['version']);
    $status = runShellCommand('git -C ' . escapeshellarg($packageDir) . ' status --porcelain -u 2>/dev/null');
    if ($status['exit_code'] !== 0 || $status['output'] !== '') {
        fwrite(STDERR, "Cannot prepare release for {$name}: working tree is not clean.\n");
        exit(1);
    }

    if (($package['pins_changed'] ?? false) === true) {
        if (!syncLocalBranch($packageDir, 'develop') || !syncLocalBranch($packageDir, 'master')) {
            fwrite(STDERR, "Cannot prepare release for {$name}: could not sync origin/develop and origin/master.\n");
            exit(1);
        }

        $currentBranch = trim((string) shell_exec(
            'git -C ' . escapeshellarg($packageDir) . ' rev-parse --abbrev-ref HEAD 2>/dev/null'
        ));
        if ($currentBranch !== 'develop') {
            runGit($packageDir, 'checkout', 'develop');
        }

        runGit($packageDir, 'reset', '--hard', 'origin/develop');

        $originMasterHead = trim((string) shell_exec(
            'git -C ' . escapeshellarg($packageDir) . ' rev-parse --verify origin/master 2>/dev/null'
        ));
        $developHead = trim((string) shell_exec(
            'git -C ' . escapeshellarg($packageDir) . ' rev-parse --verify HEAD 2>/dev/null'
        ));

        if ($originMasterHead === '' || $developHead === '') {
            fwrite(STDERR, "Cannot prepare release for {$name}: failed to resolve develop/master heads.\n");
            exit(1);
        }

        if ($developHead !== $originMasterHead) {
            $baselineCheck = runShellCommand(
                'git -C ' . escapeshellarg($packageDir) . ' merge-base --is-ancestor '
                . escapeshellarg($developHead) . ' ' . escapeshellarg($originMasterHead) . ' 2>/dev/null'
            );

            if ($baselineCheck['exit_code'] !== 0) {
                fwrite(
                    STDERR,
                    "Cannot prepare release for {$name}: develop contains commits that are not in origin/master. "
                    . "Sync the release baseline before pin refresh.\n"
                );
                exit(1);
            }

            runGit($packageDir, 'merge', '--ff-only', 'origin/master');
            if (!$noPush) {
                runGit($packageDir, 'push', 'origin', 'develop');
            }
        }

        updateComposerRequirements(
            $package['composer_path'],
            $package['updated_require'],
            $package['updated_require_dev'] ?? []
        );
        runGit($packageDir, 'add', '--', 'composer.json');
        runGit($packageDir, 'commit', '-m', 'Pin internal package versions for release ' . $tagName);

        if (!$noPush) {
            runGit($packageDir, 'push', 'origin', 'develop');
        }

        $pinCommitSha = trim((string) shell_exec(
            'git -C ' . escapeshellarg($packageDir) . ' rev-parse --verify HEAD 2>/dev/null'
        ));

        if ($pinCommitSha === '') {
            fwrite(STDERR, "Cannot prepare release for {$name}: failed to resolve pin refresh commit.\n");
            exit(1);
        }

        runGit($packageDir, 'checkout', 'master');
        runGit($packageDir, 'reset', '--hard', 'origin/master');
        runGit($packageDir, 'merge', '--ff-only', $pinCommitSha);

        if (!$noPush) {
            runGit($packageDir, 'push', 'origin', 'master');
        }
    } else {
        $currentBranch = trim((string) shell_exec(
            'git -C ' . escapeshellarg($packageDir) . ' rev-parse --abbrev-ref HEAD 2>/dev/null'
        ));
        if ($currentBranch !== 'master') {
            runGit($packageDir, 'checkout', 'master');
        }

        runGit($packageDir, 'reset', '--hard', 'origin/master');
    }

    runGit($packageDir, 'tag', '-m', 'Release ' . $tagName, $tagName, 'HEAD');

    $headSha = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' rev-parse --verify HEAD 2>/dev/null'
    ));
    $headSubject = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' log -1 --format=%s HEAD 2>/dev/null'
    ));
    $package['info']['head_sha'] = $headSha;
    $package['info']['head_sha_short'] = substr($headSha, 0, 8);
    $package['info']['head_subject'] = $headSubject !== '' ? $headSubject : '(no commit subject)';
    $package['info']['head_has_release_tag'] = true;

    if ($noPush) {
        echo ($package['pins_changed'] ?? false) === true
            ? "  Tagged {$name} {$tagName} locally after develop pin refresh and master fast-forward (not pushed)\n"
            : "  Tagged {$name} {$tagName} locally on master HEAD after pin refresh (not pushed)\n";
        return $package;
    }

    runGit($packageDir, 'push', 'origin', 'refs/tags/' . $tagName . ':refs/tags/' . $tagName);
    if (($package['pins_changed'] ?? false) === true) {
        syncAuthoringRepoBranches($packageDir, ['develop', 'master']);
    }
    echo ($package['pins_changed'] ?? false) === true
        ? "  Pushed {$name} {$tagName} after develop pin refresh, master sync, and exact pin update on {$package['info']['head_sha_short']}\n"
        : "  Pushed {$name} {$tagName} for master HEAD {$package['info']['head_sha_short']} with refreshed exact pins\n";
    return $package;
}

function developAheadOfMaster(string $packageDir): ?array
{
    // Refresh origin/develop so the ahead-count reflects the remote, not a
    // stale local ref. Releases are tag-driven from master, so unmerged develop
    // commits are the exact condition that makes finalize a silent no-op.
    fetchRemoteBranch($packageDir, 'develop');

    $developRef = trim((string) shell_exec(
        'git -C ' . escapeshellarg($packageDir) . ' rev-parse --verify --quiet refs/remotes/origin/develop 2>/dev/null'
    ));
    if ($developRef === '') {
        return null;
    }

    $count = trim((string) shell_exec(sprintf(
        'git -C %s rev-list --count master..origin/develop 2>/dev/null',
        escapeshellarg($packageDir),
    )));

    return [
        'ahead' => ctype_digit($count) ? (int) $count : 0,
        'develop_sha_short' => substr($developRef, 0, 8),
    ];
}

function printDevelopAheadWarning(array $rows): void
{
    if ($rows === []) {
        return;
    }

    echo sprintf(
        "\n\033[1;33m⚠ develop is ahead of master for %d already-tagged package(s):\033[0m\n",
        count($rows),
    );
    foreach ($rows as $row) {
        echo sprintf(
            "  \033[33m%s\033[0m  master @ %s is tagged %s, but develop @ %s is %d commit(s) ahead\n",
            $row['name'],
            $row['master_sha_short'],
            $row['tag'],
            $row['develop_sha_short'],
            $row['ahead'],
        );
    }
    echo "  Did you forget to merge develop→master? Merge via GitHub PR (or /review-prep), then re-run finalize.\n\n";
}

function collectReleaseChanges(string $packageDir, ?string $latestTag): array
{
    $range = $latestTag !== null && $latestTag !== ''
        ? $latestTag . '..master'
        : 'master';

    $cmd = sprintf(
        'git -C %s log --format=%%H%%x1f%%s %s 2>/dev/null',
        escapeshellarg($packageDir),
        escapeshellarg($range),
    );
    $output = [];
    exec($cmd, $output);

    $changes = [];
    foreach ($output as $line) {
        $line = trim($line);
        if ($line === '') {
            continue;
        }

        [$sha, $subject] = array_pad(explode("\x1f", $line, 2), 2, '');
        if ($sha === '') {
            continue;
        }

        $changes[] = [
            'sha' => $sha,
            'subject' => $subject !== '' ? $subject : '(no commit subject)',
        ];
    }

    return $changes;
}

function writeReleaseSummary(string $path, array $updatedPackages, string $rootDir, bool $noPush, bool $dryRun): void
{
    $releaseChannel = getenv('RELEASE_CHANNEL') ?: 'stable';
    $releaseCodename = getenv('RELEASE_CODENAME') ?: '';
    $releaseVersion = getenv('RELEASE_VERSION') ?: '';
    $releaseGeneratedAtUtc = getenv('RELEASE_GENERATED_AT_UTC') ?: gmdate('Y-m-d\TH:i:00\Z');

    $summary = [
        'generated_at' => gmdate(DATE_ATOM),
        'release_channel' => $releaseChannel,
        'release_codename' => $releaseCodename,
        'release_version' => $releaseVersion,
        'release_generated_at_utc' => $releaseGeneratedAtUtc,
        'root_dir' => $rootDir,
        'no_push' => $noPush,
        'dry_run' => $dryRun,
        'packages' => array_map(static function (array $package): array {
            return [
                'name' => $package['name'],
                'version' => (string) $package['version'],
                'tag' => versionTag((string) $package['version']),
                'previous_tag' => $package['info']['latest_tag'] ?? null,
                'head_sha' => $package['info']['head_sha'] ?? '',
                'head_sha_short' => $package['info']['head_sha_short'] ?? '',
                'head_subject' => $package['info']['head_subject'] ?? '',
                'changes' => $package['changes'] ?? [],
            ];
        }, $updatedPackages),
    ];

    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }

    file_put_contents(
        $path,
        json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL
    );
}

function notifyPackagistForPackages(array $updatedPackages): void
{
    $username = getenv('PACKAGIST_USERNAME') ?: '';
    $apiToken = getenv('PACKAGIST_API_TOKEN') ?: '';
    if ($username === '' || $apiToken === '') {
        echo "Tip: set PACKAGIST_USERNAME and PACKAGIST_API_TOKEN to trigger Packagist.org update.\n";
        return;
    }

    $nudgesDeclined = 0;

    foreach ($updatedPackages as $package) {
        $result = notifyPackagist($package['name'], $username, $apiToken);

        // One retry, because the failure we actually see is a burst limit. A
        // 39-package release fires 39 of these back to back; the run 20 minutes
        // later had both of its calls declined while the release itself
        // published perfectly well.
        if (!$result['ok'] && packagistWorthRetrying($result['reason'])) {
            sleep(3);
            $result = notifyPackagist($package['name'], $username, $apiToken);
        }

        if ($result['ok']) {
            echo "Packagist: triggered update for {$package['name']}\n";
            continue;
        }

        ++$nudgesDeclined;
        // NOT "failed", and not on STDERR. This call is a nudge to re-crawl
        // sooner; the tag push already fired GitHub's Packagist webhook, which
        // is the path that actually publishes. Whether the version is live is
        // decided by verifyPackagistForPackages() below, which checks both the
        // webhook delivery and packagist.org itself — so a declined nudge on a
        // run that then verifies green is noise, and printing it as a failure
        // is what makes a real failure indistinguishable from this.
        echo "Packagist: update nudge declined for {$package['name']} ({$result['reason']}); "
            . "relying on the GitHub webhook — verification below decides.\n";
    }

    if ($nudgesDeclined > 0) {
        echo "Packagist: {$nudgesDeclined} nudge(s) declined. This is only a problem if the "
            . "verification step also fails.\n";
    }
}

/**
 * Whether a nudge failure is the kind a second attempt might clear.
 *
 * Rate limits and 5xx are worth one retry. A 401/403 is a bad token and a 404 is
 * a package Packagist does not know about — retrying those just doubles the
 * noise and the wait.
 */
function packagistWorthRetrying(string $reason): bool
{
    if (str_contains($reason, 'no response')) {
        return true;
    }

    if (preg_match('/HTTP (\d{3})/', $reason, $m) !== 1) {
        return false;
    }

    $status = (int) $m[1];

    return $status === 429 || $status >= 500;
}

function verifyPackagistForPackages(array $updatedPackages): void
{
    $timeoutSeconds = max(15, (int) (getenv('PACKAGIST_VERIFY_TIMEOUT') ?: 180));
    $intervalSeconds = max(1, (int) (getenv('PACKAGIST_VERIFY_INTERVAL') ?: 5));
    $strictWebhookVerification = getenv('PACKAGIST_VERIFY_WEBHOOKS_STRICT') === '1';
    $packagistWebhookUsername = (string) (getenv('PACKAGIST_GITHUB_USERNAME') ?: getenv('PACKAGIST_USERNAME') ?: '');

    echo "Packagist: verifying webhook deliveries and published versions...\n";

    $failures = [];

    foreach ($updatedPackages as $package) {
        $packageName = $package['name'];
        $expectedVersion = versionTag((string) $package['version']);
        $expectedReference = (string) ($package['info']['head_sha'] ?? '');
        $releaseStartedAt = (string) ($package['released_at'] ?? gmdate(DATE_ATOM));

        $webhookStatus = verifyGithubWebhookDelivery($package, $packagistWebhookUsername, $releaseStartedAt, $timeoutSeconds, $intervalSeconds);
        if ($webhookStatus !== null) {
            echo $webhookStatus['message'] . "\n";
            if ($strictWebhookVerification && !$webhookStatus['ok'] && !$webhookStatus['skipped']) {
                $failures[] = $webhookStatus['message'];
            }
        }

        $published = waitForPackagistVersion($packageName, $expectedVersion, $expectedReference, $timeoutSeconds, $intervalSeconds);
        if ($published !== null && ($published['skipped'] ?? false) === true) {
            echo $published['message'] . "\n";
            continue;
        }
        if ($published === null) {
            $failures[] = "Packagist version not visible for {$packageName} {$expectedVersion}";
            continue;
        }

        $details = $published['reference'] !== ''
            ? "{$published['version']} ({$published['reference']})"
            : $published['version'];
        echo "Packagist: {$packageName} published as {$details}\n";
    }

    if ($failures !== []) {
        foreach ($failures as $failure) {
            fwrite(STDERR, $failure . "\n");
        }
        exit(1);
    }
}

/**
 * Ask Packagist to re-crawl a package.
 *
 * Returns ['ok' => bool, 'reason' => string]. It used to return a bare bool,
 * which meant a failure could only ever be reported as the word "failed" — the
 * status code and body were fetched and thrown away. Two releases printed that
 * word with no way to tell a throttle from a bad token from an outage, on runs
 * that had in fact published correctly.
 *
 * @return array{ok: bool, reason: string}
 */
function notifyPackagist(string $packageName, string $username, string $apiToken): array
{
    $url = 'https://packagist.org/api/update-package';
    $payload = json_encode(['repository' => 'https://packagist.org/' . $packageName]);
    $response = httpRequest(
        $url,
        'POST',
        $payload,
        [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $username . ':' . $apiToken,
        ],
    );

    if ($response === null) {
        return ['ok' => false, 'reason' => 'no response (network error or timeout)'];
    }

    $status = (int) $response['status_code'];
    if ($status < 200 || $status >= 300) {
        return ['ok' => false, 'reason' => 'HTTP ' . $status . packagistBodyHint($response['body'])];
    }

    $data = json_decode($response['body'], true);
    if (is_array($data) && ($data['status'] ?? null) === 'success') {
        return ['ok' => true, 'reason' => ''];
    }

    // 2xx that is not `status: success` — Packagist answering with something we
    // did not expect. Carrying the body forward is the whole point: this is the
    // branch with no status code to explain itself.
    return ['ok' => false, 'reason' => 'HTTP ' . $status . ' without status=success' . packagistBodyHint($response['body'])];
}

/** A short, single-line excerpt of a response body for an error message. */
function packagistBodyHint(string $body): string
{
    $body = trim($body);
    if ($body === '') {
        return '';
    }

    $decoded = json_decode($body, true);
    if (is_array($decoded)) {
        $message = $decoded['message'] ?? $decoded['error'] ?? $decoded['status'] ?? null;
        if (is_string($message) && $message !== '') {
            $body = $message;
        }
    }

    $body = preg_replace('/\s+/', ' ', $body) ?? $body;
    if (strlen($body) > 160) {
        $body = substr($body, 0, 157) . '...';
    }

    return ' — ' . $body;
}

function verifyGithubWebhookDelivery(array $package, string $packagistWebhookUsername, string $releaseStartedAt, int $timeoutSeconds, int $intervalSeconds): ?array
{
    if ($packagistWebhookUsername === '') {
        return ['ok' => false, 'skipped' => true, 'message' => 'Packagist webhook: skipped GitHub delivery verification (PACKAGIST_GITHUB_USERNAME not set)'];
    }

    if (!commandExists('gh')) {
        return ['ok' => false, 'skipped' => true, 'message' => 'Packagist webhook: skipped GitHub delivery verification (gh CLI not available)'];
    }

    $packageDir = (string) ($package['package_dir'] ?? '');
    $repoSlug = githubRepoSlugFromGitRemote($packageDir);
    if ($repoSlug === null) {
        return ['ok' => false, 'skipped' => true, 'message' => "Packagist webhook: skipped GitHub delivery verification for {$package['name']} (non-GitHub origin)"];
    }

    $hookId = findPackagistGithubHookId($repoSlug, $packagistWebhookUsername);
    if ($hookId === -1) {
        return ['ok' => false, 'skipped' => true, 'message' => 'Packagist webhook: skipped GitHub delivery verification (gh auth lacks admin:repo_hook scope)'];
    }
    if ($hookId === null) {
        return ['ok' => false, 'skipped' => false, 'message' => "Packagist webhook: no Packagist GitHub hook found for {$repoSlug}"];
    }

    $deadline = time() + $timeoutSeconds;
    do {
        $delivery = findRecentSuccessfulPackagistDelivery($repoSlug, $hookId, $releaseStartedAt);
        if ($delivery !== null) {
            return [
                'ok' => true,
                'skipped' => false,
                'message' => sprintf('Packagist webhook: %s delivery %s returned HTTP %d', $repoSlug, $delivery['guid'], $delivery['status_code']),
            ];
        }

        if (time() >= $deadline) {
            break;
        }
        sleep($intervalSeconds);
    } while (true);

    return ['ok' => false, 'skipped' => false, 'message' => "Packagist webhook: no recent successful delivery observed for {$repoSlug} within {$timeoutSeconds}s"];
}

function waitForPackagistVersion(string $packageName, string $expectedVersion, string $expectedReference, int $timeoutSeconds, int $intervalSeconds): ?array
{
    $deadline = time() + $timeoutSeconds;
    do {
        $version = fetchPackagistVersion($packageName, $expectedVersion, $expectedReference);
        if ($version !== null) {
            return $version;
        }

        if (time() >= $deadline) {
            return null;
        }
        sleep($intervalSeconds);
    } while (true);
}

function fetchPackagistVersion(string $packageName, string $expectedVersion, string $expectedReference): ?array
{
    $response = httpRequest('https://repo.packagist.org/p2/' . $packageName . '.json');
    if ($response === null) {
        return null;
    }

    if ($response['status_code'] === 404) {
        return [
            'skipped' => true,
            'message' => "Packagist: skipped published-version verification for {$packageName} (package not registered on Packagist)",
        ];
    }

    if ($response['status_code'] !== 200) {
        return null;
    }

    $data = json_decode($response['body'], true);
    if (!is_array($data) || !isset($data['packages'][$packageName]) || !is_array($data['packages'][$packageName])) {
        return null;
    }

    foreach ($data['packages'][$packageName] as $versionData) {
        if (!is_array($versionData) || !isset($versionData['version'])) {
            continue;
        }

        $candidateVersion = (string) $versionData['version'];
        if (normalizeVersion($candidateVersion) !== normalizeVersion($expectedVersion)) {
            continue;
        }

        $reference = (string) ($versionData['source']['reference'] ?? $versionData['dist']['reference'] ?? '');
        if ($expectedReference !== '' && $reference !== '' && $reference !== $expectedReference) {
            continue;
        }

        return ['version' => $candidateVersion, 'reference' => $reference];
    }

    return null;
}

function findPackagistGithubHookId(string $repoSlug, string $username): ?int
{
    $cmd = sprintf(
        'gh api %s --jq %s 2>&1',
        escapeshellarg('repos/' . $repoSlug . '/hooks'),
        escapeshellarg(sprintf('.[] | select(.config.url == "https://packagist.org/api/github?username=%s") | .id', $username)),
    );

    $result = runShellCommand($cmd);
    if ($result['exit_code'] !== 0) {
        if (str_contains($result['output'], 'admin:repo_hook')) {
            return -1;
        }
        return null;
    }

    $hookId = trim($result['output']);
    return ctype_digit($hookId) ? (int) $hookId : null;
}

function findRecentSuccessfulPackagistDelivery(string $repoSlug, int $hookId, string $releaseStartedAt): ?array
{
    $cmd = sprintf(
        'gh api %s --jq %s 2>&1',
        escapeshellarg('repos/' . $repoSlug . '/hooks/' . $hookId . '/deliveries'),
        // The list-deliveries endpoint reports status_code at the top level
        // and carries no `response` object at all — that exists only when
        // fetching a single delivery. Reading `.response.status_code` here
        // always yielded null, so the 2xx test below could never pass and
        // this check burned its full timeout per package on every release
        // without once succeeding. Accept either shape.
        escapeshellarg('.[] | {guid: .guid, delivered_at: .delivered_at, status: .status, status_code: (.status_code // .response.status_code)}'),
    );

    $result = runShellCommand($cmd);
    if ($result['exit_code'] !== 0) {
        return null;
    }

    $lines = array_values(array_filter(array_map('trim', explode("\n", $result['output'])), static fn(string $line) => $line !== ''));
    foreach ($lines as $line) {
        $delivery = json_decode($line, true);
        if (!is_array($delivery)) {
            continue;
        }

        $deliveredAt = (string) ($delivery['delivered_at'] ?? '');
        $status = strtoupper((string) ($delivery['status'] ?? ''));
        $statusCode = (int) ($delivery['status_code'] ?? 0);
        if ($deliveredAt === '' || strtotime($deliveredAt) === false || strtotime($deliveredAt) < strtotime($releaseStartedAt)) {
            continue;
        }
        if ($status !== 'OK' || $statusCode < 200 || $statusCode >= 300) {
            continue;
        }

        return ['guid' => (string) ($delivery['guid'] ?? 'unknown'), 'status_code' => $statusCode];
    }

    return null;
}

function httpRequest(string $url, string $method = 'GET', ?string $body = null, array $headers = [], int $timeout = 30): ?array
{
    $headerLines = array_merge(
        ['User-Agent: Semitexa-Release-Skill'],
        $headers,
    );

    $opts = [
        'http' => [
            'method' => $method,
            'header' => implode("\r\n", $headerLines) . "\r\n",
            'ignore_errors' => true,
            'timeout' => $timeout,
        ],
    ];

    if ($body !== null) {
        $opts['http']['content'] = $body;
    }

    $ctx = stream_context_create($opts);
    $response = @file_get_contents($url, false, $ctx);
    if ($response === false && empty($http_response_header)) {
        return null;
    }

    $statusCode = 0;
    if (!empty($http_response_header[0]) && preg_match('/\b(\d{3})\b/', $http_response_header[0], $m)) {
        $statusCode = (int) $m[1];
    }

    return [
        'status_code' => $statusCode,
        'body' => $response === false ? '' : $response,
    ];
}

function githubRepoSlugFromGitRemote(string $packageDir): ?string
{
    $cmd = 'git -C ' . escapeshellarg($packageDir) . ' remote get-url origin 2>/dev/null';
    $origin = trim((string) shell_exec($cmd));
    if ($origin === '') {
        return null;
    }

    if (preg_match('~github\.com[:/]([^/]+/[^/.]+)(?:\.git)?$~', $origin, $m) === 1) {
        return $m[1];
    }

    return null;
}

function versionTag(string $version): string
{
    return trim($version);
}

function latestMergedReleaseTag(string $packageDir): ?string
{
    $cmd = sprintf(
        'git -C %s tag --merged master --sort=-creatordate 2>/dev/null',
        escapeshellarg($packageDir),
    );
    $out = [];
    exec($cmd, $out);

    foreach ($out as $line) {
        $tag = trim($line);
        if ($tag === '' || !isReleaseTag($tag)) {
            continue;
        }
        return $tag;
    }

    return null;
}

function normalizeVersion(string $version): string
{
    return ltrim(trim($version), 'v');
}

function isReleaseTag(string $tag): bool
{
    $normalized = normalizeVersion($tag);
    // Semitexa release tags are UTC date-based: YYYY.MM.DD.HHMM, with optional -beta.
    // Legacy semver tags (1.0.x) are NOT release tags and must be rejected so they
    // do not silently bypass the convention or mark master HEAD as "already tagged"
    // — which would drop that package from the release with no output at all.
    return preg_match('/^\d{4}\.\d{2}\.\d{2}\.\d{4}(?:-beta)?$/', $normalized) === 1;
}

function fetchRemoteBranch(string $repoDir, string $branch): bool
{
    $cmd = sprintf(
        'git -C %s fetch --prune --tags origin %s 2>&1',
        escapeshellarg($repoDir),
        escapeshellarg($branch),
    );

    $result = runShellCommand($cmd);
    return $result['exit_code'] === 0;
}

function commandExists(string $command): bool
{
    $result = runShellCommand(sprintf('command -v %s >/dev/null 2>&1', escapeshellarg($command)));
    return $result['exit_code'] === 0;
}

function runGit(string $repoDir, string ...$args): void
{
    $cmd = 'git -C ' . escapeshellarg($repoDir);
    foreach ($args as $arg) {
        $cmd .= ' ' . escapeshellarg($arg);
    }

    $result = runShellCommand($cmd);
    if ($result['exit_code'] !== 0) {
        fwrite(STDERR, $result['output'] . "\n");
        exit($result['exit_code']);
    }
}

function runShellCommand(string $cmd): array
{
    $output = [];
    exec($cmd, $output, $exitCode);
    return [
        'exit_code' => $exitCode,
        'output' => trim(implode("\n", $output)),
    ];
}
