<?php

declare(strict_types=1);

namespace Semitexa\Dev\RemoteDeployment\Support;

final class RemoteDeployEnvBuilder
{
    public function build(?string $remoteEnvFile, ?string $domain): string
    {
        $tempPath = sprintf(
            '%s/semitexa-remote-env-%s.env',
            sys_get_temp_dir(),
            bin2hex(random_bytes(8)),
        );

        if ($remoteEnvFile !== null && trim($remoteEnvFile) !== '') {
            if (!is_file($remoteEnvFile) || !is_readable($remoteEnvFile)) {
                throw new \RuntimeException(sprintf(
                    'Remote env file "%s" does not exist or is not readable.',
                    $remoteEnvFile,
                ));
            }

            $content = file_get_contents($remoteEnvFile);
            if ($content === false) {
                throw new \RuntimeException(sprintf(
                    'Failed to read remote env file "%s".',
                    $remoteEnvFile,
                ));
            }

            file_put_contents($tempPath, $content);

            return $tempPath;
        }

        $lines = [
            '# Generated by semitexa/dev deploy:bootstrap-remote',
            'APP_ENV=prod',
            'APP_DEBUG=0',
        ];

        if ($domain !== null && trim($domain) !== '') {
            $lines[] = 'SEMITEXA_REMOTE_DEPLOY_DOMAIN=' . trim($domain);
        }

        $lines[] = '';

        file_put_contents($tempPath, implode("\n", $lines));

        return $tempPath;
    }
}
