<?php

declare(strict_types=1);

namespace Semitexa\Dev\Application\Console\Command;

use Semitexa\Core\Attribute\AsCommand;
use Semitexa\Core\Attribute\InjectAsReadonly;
use Semitexa\Core\Console\BaseCommand;
use Semitexa\Core\Discovery\ClassDiscovery;
use Semitexa\Dev\Application\Service\Capability\FrameworkCapabilityCatalog;
use Semitexa\Dev\Application\Service\Generation\Builder\PagePlanBuilder;
use Semitexa\Dev\Application\Service\Generation\Support\JsonResultFormatter;
use Semitexa\Dev\Application\Service\Generation\Support\LlmHintsFormatter;
use Semitexa\Dev\Application\Service\Generation\Support\NameInflector;
use Semitexa\Dev\Application\Service\Generation\Support\ReplayArgBuilder;
use Semitexa\Dev\Application\Service\Generation\Support\TemplateRenderer;
use Semitexa\Dev\Application\Service\Generation\Support\TemplateResolver;
use Semitexa\Dev\Application\Service\Generation\Verifier\PostWriteLinter;
use Semitexa\Dev\Application\Service\Generation\Writer\SafeFileWriter;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(name: 'make:page', description: 'Scaffold a complete page: Payload + Handler + Resource + template')]
final class MakePageCommand extends BaseCommand
{
    #[InjectAsReadonly]
    protected ClassDiscovery $classDiscovery;

    protected function configure(): void
    {
        $this
            ->addOption('module', null, InputOption::VALUE_REQUIRED, 'Target module name')
            ->addOption('name', null, InputOption::VALUE_REQUIRED, 'Page name')
            ->addOption('path', null, InputOption::VALUE_REQUIRED, 'Route path')
            ->addOption('method', null, InputOption::VALUE_REQUIRED, 'HTTP method')
            ->addOption('layout', null, InputOption::VALUE_REQUIRED, 'Layout template name')
            ->addOption('access', null, InputOption::VALUE_REQUIRED, 'Payload access type: public | protected | service', 'protected')
            ->addOption('with-assets', null, InputOption::VALUE_NONE, 'Generate CSS/JS/assets.json stubs')
            ->addOption('no-test', null, InputOption::VALUE_NONE, 'Skip the payload + handler test scaffolds (generated by default)')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Show planned files without writing (explicit)')
            ->addOption('write', null, InputOption::VALUE_NONE, 'Actually create files (dry-run is the default)')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Overwrite existing files')
            ->addOption('json', null, InputOption::VALUE_NONE, 'Output as JSON')
            ->addOption('llm-hints', null, InputOption::VALUE_NONE, 'Output LLM hints envelope');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        foreach (['module', 'name', 'path', 'method'] as $required) {
            if (!$input->getOption($required)) {
                $io->error("Missing required option: --{$required}");
                return self::FAILURE;
            }
        }

        $inflector = new NameInflector();
        $resolver = new TemplateResolver();
        $renderer = new TemplateRenderer();
        $builder = new PagePlanBuilder($inflector, $resolver, $renderer);
        $replayArgs = ReplayArgBuilder::fromInput($input, ['module', 'name', 'path', 'method', 'layout', 'access'], ['with-assets', 'no-test']);

        $plan = $builder->build([
            'module' => $input->getOption('module'),
            'name' => $input->getOption('name'),
            'path' => $input->getOption('path'),
            'method' => $input->getOption('method'),
            'layout' => $input->getOption('layout'),
            'access' => (string) $input->getOption('access'),
            'withAssets' => (bool) $input->getOption('with-assets'),
            'withTest' => !$input->getOption('no-test'),
            'dryRun' => $input->getOption('dry-run') || !$input->getOption('write'),
        ]);

        $plannedResult = new \Semitexa\Dev\Application\Service\Generation\Data\GenerationResult(
            command: 'make:page',
            status: 'dry_run',
            created: array_map(static fn($file): string => $file->path, $plan->files),
            next_steps: ['Re-run with --write to create files'],
            replay_args: $replayArgs,
        );

        if ($plan->dryRun) {
            if ($input->getOption('json')) {
                $output->writeln((new JsonResultFormatter())->format($plannedResult));
                return self::SUCCESS;
            }

            if ($input->getOption('llm-hints')) {
                $module = $inflector->toStudly($input->getOption('module'));
                $name = $inflector->toStudly($input->getOption('name'));
                $kebab = $inflector->toKebab($name);
                $formatter = new LlmHintsFormatter();
                $output->writeln($formatter->format('page_scaffold', $plannedResult, [
                    'fill_targets' => [
                        "src/modules/{$module}/src/Application/Payload/Request/{$inflector->toPayloadClass($name)}.php" => [
                            'Add properties for request parameters',
                            'Throw Semitexa\\Core\\Exception\\ValidationException from setters to reject invalid input',
                        ],
                        "src/modules/{$module}/src/Application/Handler/PayloadHandler/{$inflector->toHandlerClass($name)}.php" => [
                            'Implement business logic in handle()',
                            'Populate resource via fluent setters',
                        ],
                        "src/modules/{$module}/src/Application/Resource/Response/{$inflector->toResponseClass($name)}.php" => [
                            'Add fluent with*() setter methods',
                        ],
                        "src/modules/{$module}/src/Application/View/templates/pages/{$kebab}.html.twig" => [
                            'Build the page HTML template',
                        ],
                    ],
                    'facts' => [
                        'All three classes are auto-discovered via PHP attributes',
                        'The handler receives a hydrated payload and empty resource',
                        'Template variables are set via Resource::with() method',
                    ],
                    'constraints' => [
                        'Handler must be final class',
                        'Resource must extend HtmlResponse and implement ResourceInterface',
                        'Payload setters throw Semitexa\\Core\\Exception\\ValidationException to reject invalid input at hydration time',
                    ],
                    'mechanisms' => $this->mechanismHints(),
                    'suggested_next_prompt' => "Open the handler at src/modules/{$module}/src/Application/Handler/PayloadHandler/{$inflector->toHandlerClass($name)}.php and implement the business logic.",
                ]));
                return self::SUCCESS;
            }

            $io->title('Dry Run — Planned Files');
            foreach ($plan->files as $file) {
                $io->section($file->path);
                $output->writeln($file->content);
            }

            // Dry run is the default mode, so this is the branch most callers
            // actually see — the nudge belongs here as much as after a write.
            $this->announceMechanisms($output);
            return self::SUCCESS;
        }

        $writer = new SafeFileWriter($this->getProjectRoot(), 'make:page');
        $result = $writer->write($plan->files, (bool) $input->getOption('force'));
        $result = (new PostWriteLinter($this->getApplication()))->lintAfterWrite($result);
        $result = $result->withReplayArgs($replayArgs);

        if ($input->getOption('json')) {
            $output->writeln((new JsonResultFormatter())->format($result));
            return self::SUCCESS;
        }

        if ($input->getOption('llm-hints')) {
            $module = $inflector->toStudly($input->getOption('module'));
            $name = $inflector->toStudly($input->getOption('name'));
            $kebab = $inflector->toKebab($name);
            $formatter = new LlmHintsFormatter();
            $output->writeln($formatter->format('page_scaffold', $result, [
                'fill_targets' => [
                    "src/modules/{$module}/src/Application/Payload/Request/{$inflector->toPayloadClass($name)}.php" => [
                        'Add properties for request parameters',
                        'Throw Semitexa\\Core\\Exception\\ValidationException from setters to reject invalid input',
                    ],
                    "src/modules/{$module}/src/Application/Handler/PayloadHandler/{$inflector->toHandlerClass($name)}.php" => [
                        'Implement business logic in handle()',
                        'Populate resource via fluent setters',
                    ],
                    "src/modules/{$module}/src/Application/Resource/Response/{$inflector->toResponseClass($name)}.php" => [
                        'Add fluent with*() setter methods',
                    ],
                    "src/modules/{$module}/src/Application/View/templates/pages/{$kebab}.html.twig" => [
                        'Build the page HTML template',
                    ],
                ],
                'facts' => [
                    'All three classes are auto-discovered via PHP attributes',
                    'The handler receives a hydrated payload and empty resource',
                    'Template variables are set via Resource::with() method',
                ],
                'constraints' => [
                    'Handler must be final class',
                    'Resource must extend HtmlResponse and implement ResourceInterface',
                    'Payload setters throw Semitexa\\Core\\Exception\\ValidationException to reject invalid input at hydration time',
                ],
                'mechanisms' => $this->mechanismHints(),
                'suggested_next_prompt' => "Open the handler at src/modules/{$module}/src/Application/Handler/PayloadHandler/{$inflector->toHandlerClass($name)}.php and implement the business logic.",
            ]));
            return self::SUCCESS;
        }

        if ($result->created) {
            $io->success('Created ' . count($result->created) . ' files:');
            foreach ($result->created as $path) {
                $io->text("  - {$path}");
            }
        }
        if ($result->conflicts) {
            $io->warning('Conflicts: ' . implode(', ', $result->conflicts));
        }

        $this->announceMechanisms($output);

        return self::SUCCESS;
    }

    /**
     * The SSR mechanisms, or none when the catalog cannot be reached.
     *
     * Advice must never be the reason a generator fails. The collaborator is
     * filled by the container at boot, so a directly constructed command — every
     * scaffolding test does this — leaves the typed property uninitialised, and
     * reading it blindly turned "we could not suggest anything" into "make:page
     * is broken". Scaffolding is the job; the nudge is a bonus and degrades to
     * silence.
     *
     * @return list<array{id: string, summary: string, use_when: string, avoid_when: string,
     *                    replaces: list<string>, see_also: string, kind: string,
     *                    declared_by: string, declared_by_short: string, package: string}>
     */
    private function mechanismCatalog(): array
    {
        if (!isset($this->classDiscovery)) {
            return [];
        }

        try {
            return (new FrameworkCapabilityCatalog($this->classDiscovery))->inArea('ssr');
        } catch (\Throwable) {
            return [];
        }
    }

    /**
     * Say what the framework can already do for a page, right after scaffolding
     * one.
     *
     * This is the only one of the three capability surfaces that speaks BEFORE
     * the mistake: the catalog answers when asked, the lint objects afterwards.
     * Whatever a generator emits becomes the pattern copied for the rest of the
     * project, so a generator that mentions no mechanism teaches that there are
     * none.
     *
     * Derived from the installed packages rather than written here, so a
     * mechanism added later is offered without touching this command.
     */
    private function announceMechanisms(OutputInterface $output): void
    {
        $catalog = $this->mechanismCatalog();
        if ($catalog === []) {
            return;
        }

        $output->writeln('');
        $output->writeln('<info>Before filling this in — the framework already does:</info>');
        foreach ($catalog as $capability) {
            $output->writeln(sprintf(
                '  <comment>%s</comment>  #[%s] — %s',
                $capability['id'],
                $capability['declared_by_short'],
                $capability['use_when'],
            ));
        }
        $output->writeln('  <info>Details:</info> bin/semitexa ai:ask mechanisms --id=<id>');
        $output->writeln('');
    }

    /**
     * Mechanism list for the LLM hints envelope.
     *
     * @return list<array{capability: string, attribute: string, use_when: string, avoid_when: string}>
     */
    private function mechanismHints(): array
    {
        $out = [];
        foreach ($this->mechanismCatalog() as $capability) {
            $out[] = [
                'capability' => (string) $capability['id'],
                'attribute' => (string) $capability['declared_by'],
                'use_when' => (string) $capability['use_when'],
                'avoid_when' => (string) $capability['avoid_when'],
            ];
        }

        return $out;
    }
}
