<?php

declare(strict_types=1);

namespace Semitexa\Dev\Application\Service\Generation\Support;

final class TemplateRenderer
{
    /**
     * @param string $template Template content with {{placeholder}} markers
     * @param array<string, string> $variables Key-value pairs for substitution
     * @param string|null $generatedBy CLI command that produced this content (e.g. "make:payload").
     *                                 When set and the rendered output is PHP, a one-line
     *                                 `@generated by` footprint is injected after `declare(strict_types=1);`
     *                                 so the next agent reading the file sees the convention in code.
     */
    public function render(string $template, array $variables, ?string $generatedBy = null): string
    {
        $replacements = [];
        foreach ($variables as $key => $value) {
            $replacements['{{' . $key . '}}'] = $value;
        }

        $rendered = strtr($template, $replacements);

        if ($generatedBy !== null && $this->looksLikePhp($rendered)) {
            $rendered = $this->injectFootprint($rendered, $generatedBy);
        }

        return $rendered;
    }

    private function looksLikePhp(string $content): bool
    {
        return str_starts_with(ltrim($content), '<?php');
    }

    private function injectFootprint(string $content, string $command): string
    {
        $tag = "/** @generated by `semitexa {$command}` — scaffold; edit directly, do not regenerate to overwrite. */";

        $replaced = preg_replace(
            '/(declare\(strict_types=1\);\n)\n/',
            "$1\n{$tag}\n\n",
            $content,
            1,
            $count,
        );

        if ($replaced !== null && $count === 1) {
            return $replaced;
        }

        $fallback = preg_replace(
            '/(declare\(strict_types=1\);\n)/',
            "$1\n{$tag}\n",
            $content,
            1,
            $count,
        );

        return ($fallback !== null && $count === 1) ? $fallback : $content;
    }
}
