<?php

declare(strict_types=1);

namespace Semitexa\Dev\Application\Service\Ai\Verify;

/**
 * Layer-1 blast-radius expansion for `ai:verify`.
 *
 * When a PHP file is `DELETED` or `RENAMED` in the change set, the consumers
 * that still reference its FQCN cannot be re-verified by the existing
 * planner — they're not in the changed-file list, so `phpstan_di` never
 * scans them, and the broken `use`/typehint survives merge as a silent
 * time-bomb. This service queries the project graph for usages of the
 * removed/renamed FQCN and returns the dependent files so the planner
 * can extend its `phpstan_di` input.
 *
 * Two external dependencies, both already present at verify time:
 *   - `bin/semitexa ai:review-graph:query --usages=<FQCN> --json` for the
 *     edge query (single source of truth — same backing data the rest of
 *     the `ai:review-graph:*` family reads).
 *   - `vendor/composer/autoload_classmap.php` (regenerated by Composer on
 *     every dependency change) for the FQCN → file mapping. Composer's
 *     classmap is always current, so this step never carries the staleness
 *     risk the graph itself does.
 *
 * Self-test note: the resolver returns an empty result whenever
 *   - the change set has no DELETED/RENAMED entries,
 *   - the deleted file's FQCN cannot be derived from `autoload_psr4.php`
 *     (e.g. project root files outside a PSR-4 prefix),
 *   - the graph reports no usages,
 *   - or the graph CLI fails / is unavailable.
 * In every "I cannot tell" case the resolver yields no expansions rather
 * than emitting false-positive scan targets — `ai:verify` is shared
 * infra and a spurious expansion would break every package's verify.
 */
class ContractMoveResolver
{
    private const CLI_ARG_USAGES = '--usages=';

    /** @var array<string, list<string>>|null  PSR-4 prefix → list<absolute dir> */
    private ?array $psr4Cache = null;

    /** @var array<string, string>|null  FQCN → absolute file path */
    private ?array $classmapCache = null;

    public function __construct(
        private readonly string $projectRoot,
        private readonly ProcessRunner $processRunner = new ShellProcessRunner(),
        private readonly ?string $cliBinary = null,
    ) {}

    /**
     * @param list<ChangedFile> $files
     * @return list<ContractMoveExpansion>
     */
    public function resolve(array $files): array
    {
        $expansions = [];
        $seenFqcns  = [];

        foreach ($files as $file) {
            if (!$this->isContractMoveCandidate($file)) {
                continue;
            }

            // For a RENAME, `$file->path` is the NEW path → the NEW FQCN, but
            // orphaned consumers reference the OLD symbol. Resolve BOTH the new
            // path and (when present) the pre-rename path, so the old FQCN's
            // consumers are queried too. A DELETE has only the (old) path.
            $candidates = [['fqcn' => $this->fqcnForPath($file->path), 'file' => $file->path]];
            if ($file->status === ChangedFile::STATUS_RENAMED && $file->originalPath !== null) {
                $candidates[] = ['fqcn' => $this->fqcnForPath($file->originalPath), 'file' => $file->originalPath];
            }

            foreach ($candidates as $candidate) {
                $fqcn = $candidate['fqcn'];
                if ($fqcn === null || isset($seenFqcns[$fqcn])) {
                    continue;
                }
                $seenFqcns[$fqcn] = true;

                $dependents = $this->findDependentFiles($fqcn);
                if ($dependents === []) {
                    continue;
                }

                $expansions[] = new ContractMoveExpansion(
                    contractFqcn:   $fqcn,
                    contractFile:   $candidate['file'],
                    changeStatus:   $file->status,
                    dependentFiles: $dependents,
                );
            }
        }

        return $expansions;
    }

    private function isContractMoveCandidate(ChangedFile $file): bool
    {
        if (!str_ends_with($file->path, '.php')) {
            return false;
        }
        return $file->status === ChangedFile::STATUS_DELETED
            || $file->status === ChangedFile::STATUS_RENAMED;
    }

    /**
     * Derive an FQCN from a repo-relative PHP path using Composer's PSR-4
     * mappings. Returns null if no prefix matches — that's an honest "I
     * cannot tell" rather than a guess; the resolver swallows it as a
     * no-op for that file.
     */
    private function fqcnForPath(string $relPath): ?string
    {
        $psr4 = $this->psr4Map();
        if ($psr4 === []) {
            return null;
        }

        $absPath = $this->absolutise($relPath);

        $bestPrefix = '';
        $bestDir    = '';
        foreach ($psr4 as $prefix => $dirs) {
            foreach ($dirs as $dir) {
                $dirSlash = rtrim($dir, '/') . '/';
                if (str_starts_with($absPath, $dirSlash)
                    && strlen($dirSlash) > strlen($bestDir)
                ) {
                    $bestPrefix = $prefix;
                    $bestDir    = $dirSlash;
                }
            }
        }

        if ($bestDir === '') {
            return null;
        }

        $relInsidePrefix = substr($absPath, strlen($bestDir));
        $relInsidePrefix = preg_replace('/\.php$/', '', $relInsidePrefix) ?? $relInsidePrefix;
        if ($relInsidePrefix === '' || $relInsidePrefix === false) {
            return null;
        }

        return rtrim($bestPrefix, '\\') . '\\' . str_replace('/', '\\', $relInsidePrefix);
    }

    /**
     * @return list<string> repo-relative dependent file paths
     */
    private function findDependentFiles(string $fqcn): array
    {
        $cli = $this->cliBinary ?? $this->projectRoot . '/bin/semitexa';
        if (!is_file($cli) || !is_executable($cli)) {
            return [];
        }

        $result = $this->processRunner->run(
            [$cli, 'ai:review-graph:query', self::CLI_ARG_USAGES . $fqcn, '--json'],
            $this->projectRoot,
        );
        if ($result['exit'] !== 0 || $result['output'] === '') {
            return [];
        }

        $decoded = $this->extractJsonArray($result['output']);
        if ($decoded === null) {
            return [];
        }

        $classmap = $this->classmap();

        $files = [];
        foreach ($decoded as $edge) {
            if (!is_array($edge) || !isset($edge['source'])) {
                continue;
            }
            $sourceId = (string) $edge['source'];
            // Self-edges (e.g. an interface's implementation node mapped to its
            // own FQCN) and reflexive declarations contribute nothing — they
            // either ARE the removed contract or are noise.
            $sourceFqcn = str_starts_with($sourceId, 'class:')
                ? substr($sourceId, strlen('class:'))
                : $sourceId;
            if ($sourceFqcn === $fqcn) {
                continue;
            }
            $absFile = $classmap[$sourceFqcn] ?? null;
            if ($absFile === null) {
                continue;
            }
            $canonical = $this->canonicalisePath($absFile);
            if ($canonical === null) {
                continue;
            }
            $files[$canonical] = true;
        }

        return array_keys($files);
    }

    /**
     * @return array<string, list<string>>
     */
    private function psr4Map(): array
    {
        if ($this->psr4Cache !== null) {
            return $this->psr4Cache;
        }
        $file = $this->projectRoot . '/vendor/composer/autoload_psr4.php';
        if (!is_file($file)) {
            return $this->psr4Cache = [];
        }
        /** @var mixed $raw */
        $raw = require $file;
        if (!is_array($raw)) {
            return $this->psr4Cache = [];
        }
        $map = [];
        foreach ($raw as $prefix => $dirs) {
            if (!is_string($prefix) || !is_array($dirs)) {
                continue;
            }
            $abs = [];
            foreach ($dirs as $dir) {
                if (!is_string($dir)) {
                    continue;
                }
                $real = realpath($dir);
                $abs[] = $real !== false ? $real : $dir;
            }
            if ($abs !== []) {
                $map[$prefix] = $abs;
            }
        }
        return $this->psr4Cache = $map;
    }

    /**
     * @return array<string, string>
     */
    private function classmap(): array
    {
        if ($this->classmapCache !== null) {
            return $this->classmapCache;
        }
        $file = $this->projectRoot . '/vendor/composer/autoload_classmap.php';
        if (!is_file($file)) {
            return $this->classmapCache = [];
        }
        /** @var mixed $raw */
        $raw = require $file;
        if (!is_array($raw)) {
            return $this->classmapCache = [];
        }
        $map = [];
        foreach ($raw as $fqcn => $absFile) {
            if (is_string($fqcn) && is_string($absFile)) {
                $map[$fqcn] = $absFile;
            }
        }
        return $this->classmapCache = $map;
    }

    /**
     * Resolve a possibly-symlinked absolute path to its canonical repo-relative
     * form. Returns null when the file lives outside the project root (e.g. a
     * third-party vendor file outside our symlinked package set).
     */
    private function canonicalisePath(string $absPath): ?string
    {
        $real = realpath($absPath);
        if ($real === false) {
            $real = $absPath;
        }
        $root = rtrim($this->projectRoot, '/') . '/';
        if (!str_starts_with($real, $root)) {
            return null;
        }
        return substr($real, strlen($root));
    }

    private function absolutise(string $relPath): string
    {
        if (str_starts_with($relPath, '/')) {
            return $relPath;
        }
        return rtrim($this->projectRoot, '/') . '/' . $relPath;
    }

    /**
     * The Semitexa CLI sometimes prepends informational lines (`[INFO] …`,
     * `Container … Running`, etc.) before the JSON envelope. Pull out the
     * actual JSON array by walking lines bottom-up — the JSON payload from
     * `ai:review-graph:query --json` is a single-line array, so the last
     * line that decodes is the answer.
     *
     * @return list<mixed>|null
     */
    private function extractJsonArray(string $output): ?array
    {
        $output = trim($output);
        if ($output === '') {
            return null;
        }

        // Fast path: the whole output is a clean JSON array.
        try {
            $decoded = json_decode($output, true, 512, JSON_THROW_ON_ERROR);
            if (is_array($decoded)) {
                return $decoded;
            }
        } catch (\JsonException) {
            // fall through to per-line scan
        }

        $lines = preg_split('/\R/', $output) ?: [];
        for ($i = count($lines) - 1; $i >= 0; $i--) {
            $line = trim($lines[$i]);
            if ($line === '' || $line[0] !== '[') {
                continue;
            }
            // Skip Symfony info-prefix lines like "[INFO] …", "[WARN] …",
            // which start with `[` but aren't JSON.
            if (preg_match('/^\[[A-Z][A-Z_]*]\s/', $line)) {
                continue;
            }
            try {
                $decoded = json_decode($line, true, 512, JSON_THROW_ON_ERROR);
            } catch (\JsonException) {
                continue;
            }
            if (is_array($decoded)) {
                return $decoded;
            }
        }
        return null;
    }
}
