<?php

declare(strict_types=1);

namespace Semitexa\Dev\Tests\Unit\Generation\Builder;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Semitexa\Dev\Application\Service\Generation\Builder\TestPlanBuilder;
use Semitexa\Dev\Application\Service\Generation\Support\NameInflector;
use Semitexa\Dev\Application\Service\Generation\Support\TemplateRenderer;
use Semitexa\Dev\Application\Service\Generation\Support\TemplateResolver;

/**
 * make:test must land tests in the canonical PascalCase tests/{Integration,Unit}
 * categories, under the App\Tests\Modules\<Module>\… namespace the bootstrap
 * PSR-4 maps, and wire the payload contract test to the semitexa-testing
 * runtime. Path and namespace are kept lockstep here so the generated files
 * are discoverable and loadable without manual fixups.
 */
final class TestPlanBuilderTest extends TestCase
{
    private TestPlanBuilder $builder;

    protected function setUp(): void
    {
        $this->builder = new TestPlanBuilder(
            new NameInflector(),
            new TemplateResolver(),
            new TemplateRenderer(),
        );
    }

    #[Test]
    public function both_target_plans_a_payload_and_a_handler_test(): void
    {
        $plan = $this->builder->build([
            'module' => 'catalog',
            'name' => 'Pricing',
            'target' => TestPlanBuilder::TARGET_BOTH,
        ]);

        $paths = array_map(static fn($f): string => $f->path, $plan->files);

        self::assertSame('make:test', $plan->command);
        self::assertContains('src/modules/Catalog/tests/Integration/PricingPayloadContractTest.php', $paths);
        self::assertContains('src/modules/Catalog/tests/Unit/PricingHandlerTest.php', $paths);
    }

    #[Test]
    public function payload_test_wires_the_semitexa_testing_runtime(): void
    {
        $plan = $this->builder->build([
            'module' => 'Catalog',
            'name' => 'Pricing',
            'target' => TestPlanBuilder::TARGET_PAYLOAD,
        ]);

        self::assertCount(1, $plan->files);
        $content = $plan->files[0]->content;

        self::assertStringContainsString('namespace App\Tests\Modules\Catalog\Integration;', $content);
        self::assertStringContainsString('use Semitexa\Testing\Traits\TestsPayloads;', $content);
        self::assertStringContainsString('use TestsPayloads;', $content);
        self::assertStringContainsString('$this->assertPayloadContract(PricingPayload::class);', $content);
        self::assertStringContainsString('@generated by `semitexa make:test`', $content);
    }

    #[Test]
    public function handler_test_asserts_the_typed_handler_contract(): void
    {
        $plan = $this->builder->build([
            'module' => 'Catalog',
            'name' => 'Pricing',
            'target' => TestPlanBuilder::TARGET_HANDLER,
        ]);

        self::assertCount(1, $plan->files);
        $content = $plan->files[0]->content;

        self::assertStringContainsString('namespace App\Tests\Modules\Catalog\Unit;', $content);
        self::assertStringContainsString('use Semitexa\Core\Contract\TypedHandlerInterface;', $content);
        self::assertStringContainsString('$handler = new PricingHandler();', $content);
        self::assertStringContainsString('assertInstanceOf(TypedHandlerInterface::class, $handler);', $content);
    }

    #[Test]
    public function subject_suffix_is_not_doubled(): void
    {
        $plan = $this->builder->build([
            'module' => 'Catalog',
            'name' => 'PricingPayload',
            'target' => TestPlanBuilder::TARGET_PAYLOAD,
        ]);

        $content = $plan->files[0]->content;

        self::assertStringContainsString('PricingPayload::class', $content);
        self::assertStringNotContainsString('PricingPayloadPayload', $content);
    }
}
